# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ahi5PWE5WCcHq6BY11uOrZ3MQ16x2ZcF
"""

import numpy as np

a = np.array([1,2,3]),([2,3,4]),([3,4,5])
b = np.array([4,5,6])
print(a+b)

print(a-b)

print(a*b)

print(a/b)

print(np.power(a,5))

arr = np.array([1, 2, 3, 4])

print(arr.T)

np.zeros((3,3))

np.ones((2,4))

np.eye(4)

np.arange(1,11) #array in particular range

np.random.randint(1,100,10) #give random integer

arr = np.array([5,2,9,1])
print(np.sort(arr))

arr = np.array([1,2,2,3,3,4])
print(np.unique(arr))

a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate((a,b)))

arr = np.array([1,2,3,4,5,6])
print(np.split(arr,3))

arr = np.array([10,20,30,40,50])
print(arr[arr>25])